### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by shortboard** [brycesub/silvia-pi#14]
I've had a good crack at installing this today. I've got web app coming up but it's not reading out any values (sticking to 32 degrees) and it's not triggering the relay. I'm not sure of the best way to troubleshoot it from here.

I did notice in another thread that you said you only needed to solder 2 wires. Did I not need to solder the 6 to the thermocouple breakout? 

Thanks in advance

**Comment by brycesub** [comment]
Can you share how you've wired up the breakout, and then which pins you've connected the breakout to the pi?  Also, make sure the +/- side of the thermocouple is oriented correctly to the breakout.
