### ISSUE TITLE
Thermocouple question

### ISSUE THREAD

**Issue by jfbibeau** [brycesub/silvia-pi#15]
@brycesub Hey there - currently buying parts for the project, can you clarify if you bought the thermocouple with the mini connector or the regular spade; and if so what did you have to do to solder to the breakout board? I can't see the connection between thermocouple and breakout and the pictures... I have no issue with soldering, but was it easy to split the two wires from the mini connector?

Thanks!

**Comment by brycesub** [comment]
The mini connector unscrews easily and the thermocouple wires are held inside the connector by more screws.  Once the connector is removed the two wires are soldered to the breakout board.

**Comment by jfbibeau** [comment]
Awesome thanks for the quick reply!

**Comment by jfbibeau** [comment]
@brycesub Hi again! One more question, what type of quick connect/crimp (male?) connectors did you put at the end of the 14 gauge wires formerly connected to the brew thermostat? Any special type to make sure they fit with the existing female connectors of the Silvia? 

Something like this? https://www.fastenal.com/products/details/58569

Thanks!

**Comment by brycesub** [comment]
The link you posted isn't working (for me at the moment, might be maintenance on their side).  I got some spade terminals (at Home Depot, I think), and then used some pliers to crimp them into the existing connectors on the wires that go to the heating element.  I dug out the package, here it is:
http://i.imgur.com/QeAlLGY.jpg  AMP Spade Terminals 16-14.  Good luck!

**Comment by jfbibeau** [comment]
Thanks for the help, successful install!

![image](https://user-images.githubusercontent.com/5847314/30009121-d6be9260-90f3-11e7-9c29-c7f41c4e5057.png)
