### ISSUE TITLE
Pin 26 is always 3.3 Volts

### ISSUE THREAD

**Issue by Arkerr123** [brycesub/silvia-pi#22]
First off - Thank you for this wonderful project.  I have been disappointed with my Gaggia Classic, and I am incredibly excited to get this running!

My current setup:
1: Dashboard works, and accurately represents temp of boiler.
2: SSR light is always on - The DC wires are connected to the GPIO pins 25 and 26.  My voltmeter confirms its always on (output is 3.3VDC).
3: The output of the program in terminal does show "Heating true when cold" and Heating False when over the setpoint.  So, it appears the program is working fine.  

Do you have any suggestions as to what I can do to fix pin 26 from always being on?  Is it my board?

Thanks,
Andrew

![capture](https://user-images.githubusercontent.com/46300249/50730158-41a71d80-1114-11e9-8b82-8615da0d3672.JPG)

**Comment by adamhratcliffe** [comment]
Do you have a picture of your GPIO pinout. 

Thanks,
Adam

**Comment by Arkerr123** [comment]
![0106190959_hdr](https://user-images.githubusercontent.com/46300249/50737692-49a9a080-119a-11e9-93ef-51450e57057a.jpg)
![0106191000](https://user-images.githubusercontent.com/46300249/50737693-49a9a080-119a-11e9-8c89-710eb2007248.jpg)
![0106191000b](https://user-images.githubusercontent.com/46300249/50737694-49a9a080-119a-11e9-98fb-ab856fddf3ae.jpg)

Using a Raspberry 3 B+

**Comment by adamhratcliffe** [comment]
Try moving your white ssr wire to physical pin 37. 

Thanks,
Adam

**Comment by Arkerr123** [comment]
Works perfect now!  I did not understand the two difference between physical pin and GPIO Pin.  Thanks!

Off to taste testing now.  I will probably end up switching over to your newer version that includes a wake/sleep timer. 

Wohoo!

-Andrew
